name: AWS Auto Deploy

# - This workflow is triggered on push events to the main branch.
on:
  push:
    branches: [ "main" ]

jobs:
  deploy-aws-ec2:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up SSH for AWS
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -H #{{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        chmod 700 ~/.ssh
        echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
