name: Sample Laravel Workflow

# - This workflow is triggered on push events to the main branch.
on:
  push:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@2
      with:
        php-version: '8.3'
    - uses: actions/checkout@v4
